kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sitespeed-io
  labels:
    run: sitespeed-io
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sitespeed-io
  template:
    metadata:
      labels:
        run: sitespeed-io
    spec:
      containers:
      - name: sitespeed-io
        image: sitespeedio/sitespeed.io
        securityContext:
          privileged: true
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        volumeMounts:
          - mountPath: /sitespeed.io
            name: sitespeed-volume-claim
        resources: {}
      restartPolicy: Always
      volumes:
      - name: sitespeed-volume-claim
        persistentVolumeClaim:
          claimName: sitespeed-volume-claim