kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.2.0
        ports:
        - containerPort: 3000
        resources: {}
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: hdeAga76VG6ga7plZ1
        - name: GF_SECURITY_ADMIN_USER
          value: 'sitespeedio'
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: 'true'
        - name: GF_USERS_ALLOW_SIGN_UP
          value: 'false'
        - name: GF_USERS_ALLOW_ORG_CREATE
          value: 'false'
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-volume
      restartPolicy: Always
      volumes:
        - name: grafana-volume
          hostPath:
            path: grafana