kind: Service
apiVersion: v1
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    run: grafana
  type: NodePort
  externalTrafficPolicy: Cluster